[package]
name = "qcgpu"
version = "0.1.0"
authors = ["Adam Kelly <adamkelly2201@gmail.com>"]
documentation = "https://qcgpu.github.io/qcgpu-rust/qcgpu/index.html"
homepage = "https://github.com/qcgpu/qcgpu-rust"
readme = "./README.md"
keywords = ["quantum", "computation", "gpu", "simulation"]
license = "MIT"

[dependencies]
ocl = { git = "https://github.com/QCGPU/ocl" }
num-complex = "0.1.43"
rand = "0.4.2"

[dev-dependencies]
criterion = "0.2.1"

[[bench]]
name = "benchmark"
harness = false

[lib]
name = "qcgpu"
path = "src/lib.rs"

[[example]]
name = "bernstein-vazirani"
doc = false
path = "algorithms/bernstein-vazirani.rs"

[[example]]
name = "deutsch-jozsa"
doc = false
path = "algorithms/deutsch-jozsa.rs"

[[example]]
name = "superdense"
doc = false
path = "algorithms/super-dense.rs"

[[example]]
name = "shor"
doc = false
path = "algorithms/shor.rs"

[[example]]
name = "grover"
doc = false
path = "algorithms/grover.rs"

[[example]]
name = "simple"
doc = false
path = "examples/simple.rs"
