[package]
name = "qcgpu"
version = "0.1.0"
authors = ["Adam Kelly <adamkelly2201@gmail.com>"]
documentation = "https://qcgpu.github.io/qcgpu-rust/qcgpu/index.html"
homepage = "https://github.com/qcgpu/qcgpu-rust"
readme = "./README.md"
keywords = ["quantum", "computation", "gpu", "simulation"]
license = "MIT"

[dependencies]
ocl = "0.17"

[lib]
name = "qcgpu"
path = "src/lib.rs"

[[bin]]
name = "main"
doc = false
path = "src/bin.rs"

[[example]]
name = "grover"
doc = false
path = "examples/grover.rs"
